### ISSUE TITLE
JSON Parse Symfony 3

### ISSUE THREAD

**Issue by 7tomas7** [comur/ComurImageBundle#106]
Hi. 
Something is wrong with JSON.
I line: 
`                var options = $.parseJSON('{"uploadConfig":{"uploadRoute":"comur_api_upload","uploadUrl":"C:\\wamp64\\www\\premade\\src\\PremadeBundle\\Form\/..\/..\/..\/..\/..\/web\/uploads\/myentity","webDir":"uploads\/myentity","fileExt":"*.jpg;*.gif;*.png;*.jpeg","libraryDir":"C:\\wamp64\\www\\premade\\src\\PremadeBundle\\Form\/..\/..\/..\/..\/..\/web\/uploads\/myentity","libraryRoute":"comur_api_image_library","showLibrary":true,"saveOriginal":false,"generateFilename":true},"cropConfig":{"minWidth":588,"minHeight":300,"aspectRatio":true,"cropRoute":"comur_api_crop","forceResize":false,"thumbs":null},"fieldImage":null}');`

When I click Edit is 
`7:1 Uncaught SyntaxError: Unexpected token w in JSON at position 66
    at Function.parse [as parseJSON] (<anonymous>)
    at HTMLDivElement.<anonymous> (7:327)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.q.handle (jquery.min.js:3)`

So it cant crop.

My Form Type:
`->add('image', CroppableImageType::class, array(
                    'uploadConfig' => array(
                        'uploadRoute' => 'comur_api_upload', //optional
                        'uploadUrl' => __DIR__.'/../../../../../web/uploads/myentity', // required - see explanation below (you can also put just a dir path)
                        'webDir' => 'uploads/myentity', // required - see explanation below (you can also put just a dir path)
                        'fileExt' => '*.jpg;*.gif;*.png;*.jpeg', //optional
                        'libraryDir' => null, //optional
                        'libraryRoute' => 'comur_api_image_library', //optional
                        'showLibrary' => true, //optional
                        'generateFilename' => true   //optional
                    ),
                    'cropConfig' => array(
                        'minWidth' => 588,
                        'minHeight' => 300,
                        'aspectRatio' => true, //optional
                        'cropRoute' => 'comur_api_crop', //optional
                        'forceResize' => false, //optional
                    )
                ))`

If somebody knows what is wrong, please help.

**Comment by comur** [comment]
Too old. I close. Feel free to open new issue if you have any problem
