### ISSUE TITLE
 data.result.image_upload_file is undefined in comur.imagelibrary.js:67:1

### ISSUE THREAD

**Issue by ahmed-bhs** [comur/ComurImageBundle#109]
I'm using comur/image-bundle 1.3.x-dev f5d2237
Symfony 3.2.12
th problém that after the progress bar finish i got this execpetion witout processing the upload:
 

> data.result.image_upload_file is undefined in comur.imagelibrary.js:67:1

Index.html.twig:
```twig
{% include "ComurImageBundle:Form:croppable_image_modal.html.twig"%}
{% include "ComurImageBundle:Form:croppable_image_modal.html.twig" with {'include_jquery': true, 'include_bootstrap': true} %}
<script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
	<script src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>


	{{form(form)}}
```
by the way `console.log(data.result);` in lign 67 : `comur.image.library.js` give me this result :
```js
Object
bnbc_ajax_file_form:Array(0)
length:0
__proto__:Array(0)
__proto__:Object
```

@epidoux  @comur  @lexxpavlov  @JarJak : some help plz

**Comment by comur** [comment]
Sorry I think it's too old, I close, please open a new issue if you still have any problem
