### ISSUE TITLE
How to upload a simple Image widget with ComurImageBundle?

### ISSUE THREAD

**Issue by MarwenBenTalebAli** [comur/ComurImageBundle#110]
I'm trying to upload a image using ComurImageBundle.

Im using Symfony 3 and 1.3 branch for ComurImageBundle.

My problem: 

**I can not insert an image and the edit button does not work.**

I followed the instructions from here:[ComurImageBundle][1]

Image Entity:

    <?php
    namespace GE\CandidatBundle\Entity;
    
    use Symfony\Component\HttpFoundation\File\UploadedFile;
    use Doctrine\ORM\Mapping as ORM;
    /**
     * @ORM\Table(name="image")
     * @ORM\Entity(repositoryClass="GE\CandidatBundle\Repository\ImageRepository")
     * @ORM\HasLifecycleCallbacks
     */
    class Image
    {
        /**
         * @ORM\Column(name="id", type="integer")
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="AUTO")
         */
        private $id;
        /**
         * @ORM\Column(name="url", type="string", length=255)
         */
        private $url;
        /**
         * @ORM\Column(name="alt", type="string", length=255)
         */
        private $alt;
        /**
         * @var UploadedFile
         */
        private $file;
        
        private $tempFilename;
        /**
         * @ORM\PrePersist()
         * @ORM\PreUpdate()
         */
        public function preUpload()
        {
            if (null === $this->file) {
                return;
            }
            $this->url = $this->file->guessExtension();
            $this->alt = $this->file->getClientOriginalName();
        }
        /**
         * @ORM\PostPersist()
         * @ORM\PostUpdate()
         */
        public function upload()
        {
            if (null === $this->file) {
                return;
            }
            if (null !== $this->tempFilename) {
                $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
                if (file_exists($oldFile)) {
                    unlink($oldFile);
                }
            }
            $this->file->move(
                $this->getUploadRootDir(), 
                $this->id.'.'.$this->url  
                );
        }
        /**
         * @ORM\PreRemove()
         */
        public function preRemoveUpload()
        {
            $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
        }
        /**
         * @ORM\PostRemove()
         */
        public function removeUpload()
        {
            if (file_exists($this->tempFilename)) {
                unlink($this->tempFilename);
            }
        }
        public function getUploadDir()
        {
            return 'uploads/img';
        }
        public function getUploadRootDir()
        {
            return __DIR__.'/../../../../web/'.$this->getUploadDir();
        }
        public function getWebPath()
        {
            return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
        }
        public function getAbsolutePath()
        {
            return null === $this->image ? null : $this->getUploadRootDir().'/'.$this->image;
        }
        /**
         * @return int
         */
        public function getId()
        {
            return $this->id;
        }
        /**
         * @param string $url
         */
        public function setUrl($url)
        {
            $this->url = $url;
        }
        /**
         * @return string
         */
        public function getUrl()
        {
            return $this->url;
        }
        /**
         * @param string $alt
         */
        public function setAlt($alt)
        {
            $this->alt = $alt;
        }
        /**
         * @return string
         */
        public function getAlt()
        {
            return $this->alt;
        }
        /**
         * @return UploadedFile
         */
        public function getFile()
        {
            return $this->file;
        }
        /**
         * @param UploadedFile $file
         */
        public function setFile(UploadedFile $file)
        {
            $this->file = $file;
            if (null !== $this->url) {
                $this->tempFilename = $this->url;
                $this->url = null;
                $this->alt = null;
            }
        }
    }

Candidat Entity:

    class Candidat extends Utilisateur
    {
    /**
     * @ORM\OneToOne(targetEntity="GE\CandidatBundle\Entity\Image", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     * @Assert\Image(minWidth = 200, maxWidth = 400, minHeight = 200, maxHeight = 400)
     */
    protected $image;
    }

  CandidatType :

    //$myEntity = $builder->getForm()->getData();
            $image = new Image();
        $builder
        ->add('image', CroppableImageType::class, array(
                        'uploadConfig' => array(
                            'uploadRoute' => 'comur_api_upload', 		//optional
                            'uploadUrl' => $image->getUploadRootDir(),       // required - see explanation below (you can also put just a dir path)
                            'webDir' => $image->getUploadDir(),				// required - see explanation below (you can also put just a dir path)
                            'fileExt' => '*.jpg;*.gif;*.png;*.jpeg', 	//optional
                            'libraryDir' => null, 						//optional
                            'libraryRoute' => 'comur_api_image_library', //optional
                            'showLibrary' => true, 						//optional
                            'saveOriginal' => 'image',			//optional
                            'generateFilename' => true			//optional
                        ),
                        'cropConfig' => array(
                            'minWidth' => 588,
                            'minHeight' => 300,
                            'aspectRatio' => true, 				//optional
                            'cropRoute' => 'comur_api_crop', 	//optional
                            'forceResize' => false, 			//optional
                            'thumbs' => array( 					//optional
                                array(
                                    'maxWidth' => 150,
                                    'maxHeight' => 150,
                                    'useAsFieldImage' => true  //optional
                                )
                            )
                        )
                    ))
                ;
candidat.html.twig:

    <div class="row control-group">
        <label for="image" class="control-label col-md-3">{{ form_label(formCandidat.image) }}</label>
        <div class="controls col-md-4">
            {{ form_widget(formCandidat.image, {'attr': {'class': 'form-control'}}) }}
        </div>
        {% if form_errors(formCandidat.image) is not empty %}
            <div style="margin-bottom: 15px; height: 32px; padding: 0px 15px;"
                 class="alert alert-danger col-md-3">
                {{ form_errors(formCandidat.image.file) }}
            </div>
        {% endif %}
    </div>

In the display I got:

[![creer_compte][2]][2]

I did not get a result like Screen shots given in the details of ComurImageBundle.

When i click on the Edit Boutton i get this error in console of the navigator:

> Uncaught SyntaxError: Unexpected token x in JSON at position 66
>     at JSON.parse (<anonymous>)
>     at Function.m.parseJSON (jquery.min.js:4)
>     at HTMLDivElement.<anonymous> (inscrire:263)
>     at HTMLDivElement.dispatch (jquery.min.js:3)
>     at HTMLDivElement.r.handle (jquery.min.js:3)

**UPDATE** to fix this error i changed the methode getUploadRootDir():

    public function getUploadRootDir()
    {
        // absolute path to your directory where images must be saved
        return str_replace('\\', '\\\\', __DIR__.'/../../../../web/'.$this->getUploadDir());
    }

Now im getting this error:

> Uncaught TypeError: $(...).fileupload is not a function
>     at initializeImageManager (comur.imagelibrary.js:60)
>     at HTMLDivElement.<anonymous> (inscrire:270)
>     at HTMLDivElement.dispatch (jquery.min.js:3)
>     at HTMLDivElement.r.handle (jquery.min.js:3)
>
>GET http://localhost/uploads/img/thumbnails/9.png?1506955219395 404 (Not Found)
>
>GET http://localhost/uploads/img/thumbnails/8.png?1506963251959 404 (Not Found)
>
>GET http://localhost/uploads/img/thumbnails/6.png?1506963251960 404 (Not Found)

  [1]: https://github.com/comur/ComurImageBundle
  [2]: https://i.stack.imgur.com/FNSCY.png

**Comment by comur** [comment]
Hi,
sorry for answering almost 2 years after !!!
Did you fix your problem ? Can I close this issue ? Reopen it if you need more info / help pls.
