### ISSUE TITLE
Support of Symfony 4.0

### ISSUE THREAD

**Issue by emottet** [comur/ComurImageBundle#113]
Hi, this bundle doesn't support Symfony 4.0. is an evolution planned? Have a nice day.

**Comment by comur** [comment]
Hi,
For now I don't have any time so if someone would help (as did for SF 3) I can merge it on a new branch. Otherwise I cannot promise any planning

**Comment by comur** [comment]
Working on it now

**Comment by comur** [comment]
Latest version fully supports sf4
