### ISSUE TITLE
how upload image to database any help please!!

### ISSUE THREAD

**Issue by aimadghssisse** [comur/ComurImageBundle#114]
how upload image to database any help please!!
i do all conficuration but relation between comurImage and data do not

**Comment by comur** [comment]
Persisting in db is done by the ORM so you just have to define a property in your entity and configure it to save to DB (like any other column).
See https://github.com/comur/ComurImageBundle#image-widget at the bottom I explain how to define it :
`// YourBundle\Entity\YourEntity.php

…

/**
 * @ORM\Column(type="string", length=255, nullable=true)
 */
protected $originalImage;

…`
