### ISSUE TITLE
Can we have a new release?

### ISSUE THREAD

**Issue by localheinz** [comur/ComurImageBundle#116]
While it appears that this repository isn't active much, it has been a while since we have had a release - maybe we can have one soon?

See https://github.com/comur/ComurImageBundle/compare/1.1.0...master.

**Comment by comur** [comment]
Hi @localheinz 
Yes, I'm finally coming back after a while... Didn't have much time
I will create a new release with some bugfixes and create a changelog too. I have a new project I'm working on and will use this bundle so I can fix some bugs !
