### ISSUE TITLE
Symfony flex support

### ISSUE THREAD

**Issue by thelem** [comur/ComurImageBundle#121]
I have been moving my application from Symfony 3 to Symfony 4 with Flex, but that gives me the error

> Template reference "ComurImageBundle:Form:croppable_image_modal.html.twig" not found, did you mean "@ComurImage/Form/croppable_image_modal.html.twig"?

The stack trace shows this coming from my template

`{{ form_start(form) }}`

Doing some digging, the offending line is actually in comur\image-bundle\DependencyInjection\Compiler\FormPass.php

If, as suggested, I change the line
`        $template = "ComurImageBundle:Form:croppable_image_modal.html.twig";`
to
`        $template = "@ComurImage/Form/croppable_image_modal.html.twig";`

then the problem seems to be solved.

Reviewing the documentation I can see that the first syntax is recommended for 3.1
https://symfony.com/doc/3.1/templating.html#referencing-templates-in-a-bundle

The later syntax is recommended for 3.2 to master (which is 5.1 as I write this)
https://symfony.com/doc/3.2/templating.html#referencing-templates-in-a-bundle
https://symfony.com/doc/master/templates.html#bundle-templates

I'm going to work on a PR to change to the newer syntax. Minimum supported version is already 3.4, so breaking compatibility with 3.1 should not be an issue.

**Comment by thelem** [comment]
I've made those code changes at https://github.com/thelem/ComurImageBundle/tree/thelem/121

I'll do more testing before opening a pull request. The readme will also need to be updated.

**Comment by comur** [comment]
Hi @thelem 
Thanks for this work. It's weird as I already use it with SF 4.3 on 2 other projects without any issue... But I understand that it causes a problem as template path specification has been changed from 3.4 so I let you send the PR and I will merge it.
Thx

**Comment by thelem** [comment]
Symfony wasn't picking up the routing file unless I manually include it. I've added instructions to the readme to do this, based on the instructions provided for FOS JS Routing at https://symfony.com/doc/master/bundles/FOSJsRoutingBundle/installation.html
