### ISSUE TITLE
comur + bootstrap when click edit

### ISSUE THREAD

**Issue by elgui02** [comur/ComurImageBundle#14]
Hi a try use the bundle when i click on edit my navegator says:

Uncaught TypeError: undefined is not a function 
on  $('#image_upload_file').fileupload
i include  {% include "ComurImageBundle:Form:croppable_image_modal.html.twig" with {'include_jquery': true, 'include_bootstrap': false} %} do you have any idea?

**Comment by airtonfjunior** [comment]
I install but have the same error

Uncaught TypeError: undefined is not a function comur.imagelibrary.js:60
$('#image_upload_file').fileupload

can you help me?
