### ISSUE TITLE
Placehold.io does not work

### ISSUE THREAD

**Issue by Tersoal** [comur/ComurImageBundle#29]
Hi all!!!

It seems that placehold.io doesn't work, the web is offline. It can be replaced by placehold.it, but I recommend to use holder.js, thus the bundle doesn't depend on outer functions.

http://imsky.github.io/holder/

**Comment by comur** [comment]
Hi tersoal

can you send me a PR for this issue ?

thanks

**Comment by comur** [comment]
https://placehold.io/589/300

For me it's working but your idea is better to not depend on outer systems so if you have any time to send me a PR i can merge it, thanks.

i was using placehold.it but it does not support https...

**Comment by Tersoal** [comment]
Sorry, I'm not skilled with github and forks. Can't you see the last commit?

**Comment by AlexLwm** [comment]
hye can you push url replacement on v1.0 branche please

**Comment by comur** [comment]
I did it in a better (i think) way by including holderjs in composer. I have to test it

**Comment by comur** [comment]
Well it's not working for now, i have to find a solution to publish holder.js in assets but without copying it in the bundle. If we copy, we cannot update holderjs.

So i will use a cdn for now, if someone has a solution for this i will appreciate :)
