### ISSUE TITLE
Error with *.png transparency

### ISSUE THREAD

**Issue by AlexLwm** [comur/ComurImageBundle#30]
When I crop a file png with background transparent
I have a black background
I think you must add  imagealphablending on each new layer.

**Comment by comur** [comment]
Hi @AlexLwm 

can you send me your image that i can test and try to add a patch pls ?

thanks

**Comment by AlexLwm** [comment]
![laptop](https://cloud.githubusercontent.com/assets/4696362/5626843/19326b00-9591-11e4-8595-1a6c661376b0.png)

Sure in this file le screen laptop is transparent.

Personaly I have change init_crop to have a background white

And I have change uploadController.php 

in function resizeCropImage

         $dstR = imagecreatetruecolor( $destW, $destH );
        //imagealphablending($dstR, false);
        //imagecopyresampled($dstR,$imgR,$destX,$destY,$srcX,$srcY,$destW,$destH,$srcW,$srcH);

        imagealphablending($dstR, false);
        $col=imagecolorallocatealpha($dstR,255,255,255,127);
        imagefilledrectangle($dstR,0,0,$destW, $destH,$col);
        imagealphablending($dstR,true);

        imagecopyresampled($dstR,$imgR,$destX,$destY,$srcX,$srcY,$destW,$destH,$srcW,$srcH);
        imagealphablending($dstR,true);
        imagesavealpha($dstR, true);

**Comment by comur** [comment]
Can you confirm if it's ok or not for you pls ?

**Comment by AlexLwm** [comment]
It s ok
Thank's

2015-01-06 11:19 GMT+01:00 Can OMUR <notifications@github.com>:

> Can you confirm if it's ok or not for you pls ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/comur/ComurImageBundle/issues/30#issuecomment-68848619>
> .
>



-- 
Alexandre HUBERT

Bureau :0230961981[image: LWM Agence : agence digitale]
www.lwm-agence.com <http://www.lwm-agence.com/>Standard Paris :01 44 77 99
44Standard Rennes :02 30 96 14 09Fax :01 44 77 99 40[image: LWM Agence :
Suivez-nous sur Twitter] <http://twitter.com/lwm_agence>    [image: LWM
Agence : Rejoignez-nous sur Facebook]
<http://www.facebook.com/pages/LWM-agence-digitale/391932214186500>
