### ISSUE TITLE
Modal window not responsive

### ISSUE THREAD

**Issue by Tersoal** [comur/ComurImageBundle#33]
Hi.

the modal is not responsive, and in mobiles is not functional. There is a fixed width to 850px, but i don't know why. There is a reason for that? If you delete it, the modal works perfectly.

Cheers,
Sergio

**Comment by emottet** [comment]
Hi. Same question here. Indeed, by commenting `width: 850px;` in `comur.image_bundle.css`, it works just fine on smartphones. 
Cheers,
Emmeline

**Comment by comur** [comment]
Hi,
Is it also ok on desktop when commenting fixed width ? if so, can you send a PR please so I can merge ?
Thanks
Cheers
