### ISSUE TITLE
I can't get it to work :(

### ISSUE THREAD

**Issue by Xyr2** [comur/ComurImageBundle#37]
Hey there,
I installed the lates dev-master as described in the documentation, but can't get it to work.
If I hover over the placeholder Image the Edit button appears, but pressing it doesn't work.
In the console I see this error when pressing the Edit button:
TypeError: $(...).fileupload is not a function
Empty string passed to getElementById().

Jquery and all necessary files are loaded and active. What could be the problem?

Thanks for help.. :)

**Comment by comur** [comment]
Hi @Xyr2 

Which version of Bootstrap do you use in your project ? If it's the latest, you need to install branch 1-dev as described in README at first line.

Tell me if it was that

**Comment by comur** [comment]
I suppose that your problem is solved ?
