### ISSUE TITLE
Modal doesnt appear

### ISSUE THREAD

**Issue by DavidPuleri** [comur/ComurImageBundle#38]
I manage to get the holder displayed properly but when I click on Modify, the background become darker as it would be expected but no modal and no error / warning / anything to debug.

Jquery 2.1
Bootstrap 3.2.2
Query UI Widget 1.10.3+amd (provided by your bundle)

Thanks for your help!

**Comment by comur** [comment]
Hi @DavidPuleri 

Which branch do you use ? 1-dev ? With Bootstrap 3 you have to use 1.x branch

**Comment by DavidPuleri** [comment]
Hi

Thanks for replying so quickly. I am now using 1.0.2 but the console errors there : http://placehold.io/300/250.
I think that there is a type there :
 
 <img src="//placehold.io/{{ options.cropConfig.minWidth }}/{{ options.cropConfig.minHeight}}" id="{{ form[name].vars.id }}_preview"/>

Also,  when i click on use it, the preview disappears and I cant get it back

thx

**Comment by comur** [comment]
Can you use 1-dev pls ? I fixed some issues recently

**Comment by DavidPuleri** [comment]
ok, it looks better. The cropped image doesnt appear. I suspect it to be a path issue but the configuration seems ok. the cropped and original files are in the right folder but the browser doesnt display and loose the modifiy button

**Comment by comur** [comment]
I need more detail about your code to help you on this issue,
can you check in inspector to see what you have instead of cropped image ?

**Comment by DavidPuleri** [comment]
The image is properly cropped

This is the preview thumbnail that is not being displayed.

<img src="/uploads/image/cropped/thumbnails/300x250-be2ac7a541be27d9ac79c4b420156e60683c3221.jpg?1425915230275" id="lpi_sitebundle_image_filename_filename_preview" width="0" height="0" style="display: none !important; visibility: hidden !important; opacity: 0 !important; background-position: 0px 0px;">

This file does exist. Is there something overriding the display somewhere deep in the css ?

**Comment by apsylone** [comment]
Same problem here with @dev-master version.
Using : 
- jQuery 1.10.2
- jQueryUI 1.9.2
- Boostrap v3.2.0

No error JS in console. But some networks error (404) for a placeholder : 
http://www.mydomain.com/mycontroller/myaction/holder.js/200x200

Hope this would help for debugging !

**Comment by comur** [comment]
Hi @apsylone 

Same answer :) With Bootstrap 3 you have to use 1.x branch.

Hope it helps

**Comment by apsylone** [comment]
Hum... You're right :+1: 
I've posted too  fast !

Next time, I will read the doc first :smile: 

Thanks,
