### ISSUE TITLE
png transparent background turned black

### ISSUE THREAD

**Issue by Tersoal** [comur/ComurImageBundle#39]
Hi again.

There is an issue with png files that has transparent background. I have resolved it.
- In comur.image.library.js jcrop initialization must be bgColor: 'transparent' insteada of bgColor: 'black'.
- In UploadController.php, line 337, the transparency is doing after other functions that breaks it. It must be moved to line 325, inmediately after imagecreatetruecolor call and before imagecopyresampled call.

**Comment by comur** [comment]
Hi,

Thanks i will do it A.S.A.P.

**Comment by comur** [comment]
Too old. I close. Feel free to open new issue if you have any problem
I think it’s ok with last release
