### ISSUE TITLE
Uncaught SyntaxError: Unexpected token i

### ISSUE THREAD

**Issue by yannskee** [comur/ComurImageBundle#40]
Hello i having this problem: "Uncaught SyntaxError: Unexpected token i" when I click on the "Edit" button where I included the image widget in my view.

I use the branch : "comur/image-bundle": "1.0.*@dev"
and bootstrap 3.

In my layout I used {% include "ComurImageBundle:Form:croppable_image_modal.html.twig" with {'include_jquery': false, 'include_bootstrap': false} %} since i'm already including a jquery script and bootstrap 3. I made sure the include was after the jquery script.

When i click on the error msg in the navigator console. i don't get a specific line number, so i have no idea where the error is coming from.

**Comment by yannskee** [comment]
I found the source of the problem. The issue is caused because I am using windows and the path generated by this :
public function getUploadRootDir()
{
    // absolute path to your directory where images must be saved
    return __DIR__.'/../../../../../web/'.$this->getUploadDir();
}
has backslashes instead of foward slash on Linux. So there is a conflict with Javascript and JSON.

This seemed to have fixed the issue: 

    public function getUploadRootDir()
    {
        // absolute path to your directory where images must be saved
        return str_replace('\\', '\\\\', __DIR__.'/../../../../web/'.$this->getUploadDir());
    }

**Comment by NajibOX** [comment]
thanks yannskee it work with me .

**Comment by ignas3run** [comment]
I had the same problem. Please update documentation. It took me some time to find an answer. Thank you yannskee!

**Comment by comur** [comment]
It’s not necessary now since someone sent a PR for this problem. I close it
