### ISSUE TITLE
upload doesn't work in IE10

### ISSUE THREAD

**Issue by ekittell** [comur/ComurImageBundle#45]
Nothing happens when you select a file.  I see where it calls _initIframeSettings in jquery.fileupload.js but that doesn't seem to do much.  In other browsers it doesn't call that method, it uses XHR upload instead and that seems to work fine.

edit: this is actually IE9 issue, it works with XHR in IE10

**Comment by comur** [comment]
Too old. I close. Feel free to open new issue if you have any problem
