### ISSUE TITLE
Field not marked as error

### ISSUE THREAD

**Issue by fliespl** [comur/ComurImageBundle#47]
When using Assert/NotBlank on image field, the label is not colored and error isn't shown. Example of correct behaviour (title) and broken one (image):

http://codeone.pl/ss/ss-2015-07-12_19-42-55-001.png

**Comment by jokari4242** [comment]
+1

**Comment by comur** [comment]
Hi,

Can someone make a PR for this issue ? If not, I will try to check it soon.
