### ISSUE TITLE
Jquery error : $(...).sortable is not a function

### ISSUE THREAD

**Issue by 5t3ff** [comur/ComurImageBundle#53]
Hi,

When I want to use the image gallery widget I get this error in the browser console. I have to download jquery ui and add it to the croppable_image_modal.html.twig template to get it work. I use jquery v2.1.4, I get this error event if I set the "include_jquery" parameter to TRUE. Don't think it's normal or if I've miss something ?

Thx

**Comment by glerendegui** [comment]
Hi. 
I have faced this problem too. I have started a new project from scratch. The main problem seems to be that this bundle is not including jquery-ui sortable javascript, only the widget one.
Worked after download jquery-ui.js (with sortable plugin) and be added to croppable_image_modal.html.twig like this:

<script src="{{ asset('bundles/app/js/jquery-ui.js') }}"></script>
<script src="{{ asset('bundles/comurimage/js/jquery.ui.widget.js') }}"></script>
