### ISSUE TITLE
Animated GIF support

### ISSUE THREAD

**Issue by AlexLwm** [comur/ComurImageBundle#56]
I have an error with size of gif.
In UploaderHandler  line 944 pingImage no return good value for width and height file
I test with this picture

![test](https://cloud.githubusercontent.com/assets/4696362/9714900/d12608b8-555b-11e5-9169-d2a467b42547.gif)

**Comment by comur** [comment]
Hi @AlexLwm 

Thanks for report but i never tester with animated gifs so it's not supported  for now. If you want to send a PR to implement it, no pb :)

**Comment by comur** [comment]
I will work on it next week

**Comment by comur** [comment]
Fixed but needs Imagick to work. If you don't have Imagick installed, it will return not animated image as GD does not manage multi frame images
