### ISSUE TITLE
Working with sonata media

### ISSUE THREAD

**Issue by ruscon** [comur/ComurImageBundle#58]
Could this library potentially work with sonata media ?
May be as some extension as CoopTilleulsCKEditorSonataMediaBundle

**Comment by comur** [comment]
Hi,

I created this bundle to use instead of sonata media (when it only concerns images) because I think that it's too complicated for just managing medias (keep it simple stupid).

If you want to try and send me a PR, I can check and merge it but I never tested the bundle with sonata media.

**Comment by ruscon** [comment]
Ok, thx
