### ISSUE TITLE
Uncaught TypeError: $(...).fileupload is not a function

### ISSUE THREAD

**Issue by anthonyherve** [comur/ComurImageBundle#59]
Hello,

I have installed your bundle that is very great but I have a problem when I click on Edit button : 
    Uncaught TypeError: $(...).fileupload is not a function

Here is my versions : 
* bootstrap : 3.3.x-dev
* jQuery : 2.1.4
* ComuImageBundle : 1.0.*@dev

I include Twig like this : 
{% include "ComurImageBundle:Form:croppable_image_modal.html.twig" with {'include_jquery': false, 'include_bootstrap': false} %}

I have installed assets and all JS are present in web/bundles folder.

If I comment .fileupload from comur.imagelibrary.js, I have another problem with function modal from bootstrap : Uncaught TypeError: $(...).modal is not a function. Very strange...

But if I copy this line ($('#image_upload_modal').modal('show');) from comur.imagelibrary.js to the end of my HTMl document, it works and modal appears.

I don't understand what it's happening...

If someone has an idea, thank you.

**Comment by comur** [comment]
Hi,

Can you try to use master ? 1.0.* is not the latest release.

If it's not ok, can you check if you don't have another error before Uncaught TypeError: $(...).fileupload is not a function and before clicking on edit button ? I think maybe you include jquery at the end of your document and croppable_image_modal.html.twig needs it because of other depending libraries.

You can also try to use include_jquery / bootstrap to check if error is related to this and not including them by yourself ?

**Comment by anthonyherve** [comment]
Hi,

Thanks for answer. Unfortunately, I tried to use dev-master, no effect. I include jquery and bootstrap and not myself, no effect.

Here is a part of HTML page : 
```html
<!-- The jQuery script, can be omitted if jQuery is already included -->
    <script src="/bundles/comurimage/js/jquery.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/bundles/comurimage/js/jquery.ui.widget.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/bundles/comurimage/js/jquery.iframe-transport.js"></script>
<script src="/bundles/comurimage/js/jquery.fileupload.js"></script>
<script src="/bundles/comurimage/js/jquery.Jcrop.min.js"></script>
<script src="/bundles/comurimage/js/jquery.color.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.5.2/holder.min.js"></script>
    <script src="/bundles/comurimage/js/bootstrap.min.js"></script>
<!-- ComurImageBundle script. Do not remove this -->
<script src="/bundles/comurimage/js/comur.imagelibrary.js"></script>
```

I don't include jquery and bootstrap myself but it's not working.

I have no other error. It's very weird...

Have you another idea ?

**Comment by comur** [comment]
And do you have any 404 in loaded files / scripts ? Can you check in inspector that you have all files successfully loaded ?

**Comment by comur** [comment]
I think it's the same problem as #53 maybe related to jquery ui

**Comment by anthonyherve** [comment]
No 404 error in loaded files / scripts as you can in this capture.
![loaded-files](https://cloud.githubusercontent.com/assets/1899492/11241553/fe4faffa-8dfb-11e5-92e4-6c06b09ff192.JPG)

I have already include jquery-ui file.

Maybe a problem of version ... ?

**Comment by anthonyherve** [comment]
OK I found the problem. It's not from your bundle, but I did not think so. :-)
It's from another bundle which imports a jquery version and there was a conflict.

Thank you for your help and continue your good work with this bundle.
