### ISSUE TITLE
Generates filename when i use 'generateFilename' => false

### ISSUE THREAD

**Issue by chrislebaron** [comur/ComurImageBundle#69]
Here is my entityType.php code

`->add('imgName', 'comur_image', array(
                'uploadConfig' => array(
                    'generateFilename' => false,
                    'showLibrary' => false,
                    'uploadUrl' => $myEntity->getUploadRootDir(),
                    'webDir' => $myEntity->getUploadDir(),
                    'fileExt' => '*.jpg;*.gif;*.png;*.jpeg',
                ),
                'cropConfig' => array(
                    'minWidth' => 200,
                    'minHeight' => 200,
                    'aspectRatio' => true,
                    'cropRoute' => 'comur_api_crop',
                    'forceResize' => true,
                )
            ))`

So with or with the `'generateFilename' => false` set to true or false it always sets the filename to a super long ugly string like 271ed3895ece9653fb0c31a6793142b8e811d404.jpg

**Comment by comur** [comment]
Hi @chrislebaron 

Can you check version of the bundle you use pls ?
You must use dev-master to have this parameter

**Comment by chrislebaron** [comment]
Don't I feel sheepish... I wasn't on dev, I was on 1.1
