### ISSUE TITLE
croppable_image_modal.html.twig don't work

### ISSUE THREAD

**Issue by NadaBen** [comur/ComurImageBundle#70]
Hello, when i add {% include "ComurImageBundle:Form:croppable_image_modal.html.twig"%} it shows me nothing and when i add {% include "ComurImageBundle:Form:croppable_image_modal.html.twig" with {'include_jquery': false, 'include_bootstrap': false} %}   it works without style, how to fix that please ?

**Comment by comur** [comment]
Hello @NadaBen 

Please check inspector errors and send me what you have as error. You can also check inspector when you click on button to see if you have any error (JS, 404...)

**Comment by NadaBen** [comment]
How can i check inspector errors please ?

**Comment by comur** [comment]
[https://www.google.fr/search?q=webkit+inspector&ie=utf-8&oe=utf-8&gws_rd=cr,ssl&ei=1t09V5rAJoGTadXinsgP#newwindow=1&q=browser+inspector](https://www.google.fr/search?q=webkit+inspector&ie=utf-8&oe=utf-8&gws_rd=cr,ssl&ei=1t09V5rAJoGTadXinsgP#newwindow=1&q=browser+inspector)

**Comment by NadaBen** [comment]
![capture](https://cloud.githubusercontent.com/assets/11770242/15402879/9f341ac0-1df6-11e6-8976-3ad9badbf5b5.PNG)

**Comment by comur** [comment]
You need to look at console and network to see errors

**Comment by NadaBen** [comment]
it shows me nothing
