### ISSUE TITLE
edit image already saved

### ISSUE THREAD

**Issue by halhnini** [comur/ComurImageBundle#71]
Hi
i want to edit image profile using ComurImageBundle but i don't know what should i write is any documentation or any code already used.thanks

**Comment by comur** [comment]
Hi @halhnini 

You can start by reading [Usage section in README](https://github.com/comur/ComurImageBundle/blob/master/README.md#usage)

**Comment by halhnini** [comment]
Hi,
Thank you for your help @comur ,i already use it and it works fine but now i need to make like the first capture 
![com](https://cloud.githubusercontent.com/assets/12613432/15739404/cf6f2e62-28a7-11e6-9042-59adec0f586a.png)

**Comment by comur** [comment]
You simply use your field in your form template (twig file) as a regular field, ex:
`
{{ form_widget(image) }}
`

**Comment by halhnini** [comment]
ok,but how to set the field image by the path image from entity field,
thank you.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
