### ISSUE TITLE
edit image already saved

### ISSUE THREAD

**Issue by halhnini** [comur/ComurImageBundle#72]
Hi,
Thank you for your help @comur ,i already use it and it works fine but now i need to make like the first capture 
![com](https://cloud.githubusercontent.com/assets/12613432/15739652/ef623a56-28a8-11e6-8dcf-f5c22a06d72b.png)

**Comment by YuriyKvit** [comment]
+1

**Comment by Bigg-Mike** [comment]
+ 1

**Comment by comur** [comment]
Please check with the last release
