### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by goose74** [comur/ComurImageBundle#73]
Hi thank for your work @comur 

Everything looks ok for me but still I have a 404 error  :

Upload seems to work, file is on the server at the right place with the getUpload method on my Entity.

But the view doesn't show it to me:

<img width="1440" alt="capture d ecran 2016-06-08 a 01 27 54" src="https://cloud.githubusercontent.com/assets/7041923/15878058/4a27c456-2d18-11e6-9887-b342a45b6163.png">

Why is he looking for http://localhost/img/... ?
He should look for something like http://localhost/myproject/web/img... no?

Thanks for your help.

Regards

**Comment by comur** [comment]
Hi @goose74 
I depends on how you configured your web server, what is your project's home url ? http://localhost/myproject ?
I suggest you to configure a vhost (apache / nginx) to have a host for your project like myproject.localhost for ex. Like this you can have a config similar of production

As a workaround (but it's dirty and not recommended as it won't work on production env) you can change getWebPath function of your entity and add /myproject/ at the beginning of path returned:

`
public function getWebPath()
{
    return null === $this->image ? null : '/myproject/'.$this->getUploadDir().'/'.$this->image;
}
`
