### ISSUE TITLE
help. I can not make it work. Not appear the button to add image. 

### ISSUE THREAD

**Issue by yumoraes** [comur/ComurImageBundle#76]
My code:
Controler:
`    /**
     \* @Route("/pacote/novoPacote", name="friendstrip.app.pacotes.novoPacote")
     \* @Template("FriendstripAppBundle:Pacotes:novoPacote.html.twig");
     */
    public function novoPacoteAction(Request $request)
    {
        $pacote = new AppBundle\Entity\Pacote();

```
    $form = $this->createFormBuilder($pacote)
         ->add('image', 'comur_image', array(
            'uploadConfig' => array(
                'uploadRoute' => 'comur_api_upload',        //optional
                'uploadUrl' => $pacote->getUploadRootDir(),       // required - see explanation below (you can also put just a dir path)
                'webDir' => $pacote->getUploadDir(),              // required - see explanation below (you can also put just a dir path)
                'fileExt' => '*.jpg;*.gif;*.png;*.jpeg',    //optional
                'libraryDir' => null,                       //optional
                'libraryRoute' => 'comur_api_image_library', //optional
```

//                    'showLibrary' => true,                      //optional
//                    'saveOriginal' => 'originalImage',          //optional
                    'generateFilename' => true          //optional
                ),
                'cropConfig' => array(
                    'minWidth' => 588,
                    'minHeight' => 300,
                    'aspectRatio' => true,              //optional
                    'cropRoute' => 'comur_api_crop',    //optional
                    'forceResize' => false,             //optional
                    'thumbs' => array(                  //optional
                        array(
                            'maxWidth' => 180,
                            'maxHeight' => 400,
                            'useAsFieldImage' => true  //optional
                        )
                    )
                )
            ))
            ->getForm();

```
return ['form' => $form->createView(),];
}`
```

twig view:
` <div  class="tab-pane" id="fotos">
                    <div class="form-group">
                        {{ form_widget(form) }}

```
                </div>
            </div>`
```

show:
![comur](https://cloud.githubusercontent.com/assets/19959843/16207915/05ce654c-3706-11e6-8cf3-2913464fb800.PNG)

**Comment by comur** [comment]
Hi @yumoraes 
please check in your web inspector to see if you have any 404 or JS errors. I think it's an asset issue

**Comment by paulmonty** [comment]
@comur your solution looks great, but I struggle to install it in Sonata. 

I got a lot of 404s
![zrzut ekranu 2016-07-24 o 01 51 17](https://cloud.githubusercontent.com/assets/20618556/17080885/66288fee-5141-11e6-8b9c-921aceffede9.png)

and my field looks like this
![zrzut ekranu 2016-07-24 o 01 51 27](https://cloud.githubusercontent.com/assets/20618556/17080884/65fbd3d2-5141-11e6-9a00-2b5a69a035eb.png)

I pasted
            <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
            <script src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>
        {% include "ComurImageBundle:Form:croppable_image_modal.html.twig"%}

to standard_layout.html.twig in sonata-project/admin-bundle resources folder.

I would appreciate your help.

**Comment by JuanWilde** [comment]
Try to perform a "php app/console assets:install --symlink" and it should work

**Comment by comur** [comment]
@paulmonty is it ok with @JuanWilde 's solution ? can we close this issue ?

**Comment by comur** [comment]
Too old. I close. Feel free to open new issue if you have any problem
