### ISSUE TITLE
Nothing happens when clicking on "Add image" button 

### ISSUE THREAD

**Issue by kikdu** [comur/ComurImageBundle#78]
Hi,

When I click on "Add image", nothing happens. 

In my web inspector I have this JS error :

> SyntaxError: JSON.parse: bad escaped character at line 1 column 67 of the JSON data

In my view I have added

`{% include "ComurImageBundle:Form:croppable_image_modal.html.twig"%}`
`<script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>`
`<script src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>`

and I linked jquery, jquery ui, ... so I don't understand why it doesn't work. 

And in my composer.json : 
     `   "comur/image-bundle": "1.1.0",`
      `  "friendsofsymfony/jsrouting-bundle": "1.6.0", `
       ` "jms/translation-bundle": "1.2.0"  `

Any idea ?

**Comment by kikdu** [comment]
Ok it's because i'm on Windows. 

>SyntaxError: JSON.parse: bad escaped character at line 1 column 67 of the JSON data

On windows there is a problem with the / and the \ . 

I have seen here that somebody had the same issue but it was 2 years ago and his solution doesn't work with 1.3. 

Can we work with ComurImageBundle 1.3 on Windows ? For development phase.

**Comment by ZIMkaRU** [comment]
`public function getUploadRootDir()`
`    {`
`        // absolute path to your directory where images must be saved`
`        $dir = strtoupper(substr(PHP_OS, 0, 3)) === 'WIN' ? str_replace('\\', '/', __DIR__) : __DIR__;`
`        return $dir.'/../../../../web/'.$this->getUploadDir();`
`    }`

**Comment by kikdu** [comment]
Thanks ! The upload window pops up correctly now. 

But when I upload an image I have : 

GET 
http://localhost/images/gallery/thumbnails/0028febdef65f75ccb123aa9a328489c2e31f0a4.jpg [HTTP/1.1 404 Not Found 5 ms]

On my JS console.

Somebody knows why ?

My standard url is http://localhost/Symfony3/web/app_dev.php/index

**Comment by ZIMkaRU** [comment]
The URL should be http://localhost/Symfony3/app_dev.php/index

**Comment by ZIMkaRU** [comment]
Add ".htaccess" file in the root of the project with the code:
```
<IfModule mod_negotiation.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/web/.*$
    RewriteRule ^(.*)$ /web/$1 [QSA,L]
</IfModule>
```

**Comment by kikdu** [comment]
Thanks it's ok !
