### ISSUE TITLE
Division by Zero when "Crop And Save" button is pressed

### ISSUE THREAD

**Issue by JuanWilde** [comur/ComurImageBundle#81]
I'm using this awesome bundle and apparently all is fine. But when I press the Save button I get this error
![image](https://cloud.githubusercontent.com/assets/6040385/18084831/031d2e5c-6ea9-11e6-91bc-01cdc86cbc4d.png)

The same in line 343
![image](https://cloud.githubusercontent.com/assets/6040385/18086747/b34e91f0-6eb1-11e6-866a-769ace6bb05d.png)

Any idea?

**Comment by comur** [comment]
Apparently there is a problem with your image or you selection but anyway we should put a check on srcH and destH to be sure that it's > 0
Can you check these values by adding a var_dump or something ?

**Comment by JuanWilde** [comment]
Yes. What I did is to check if those values were > 0 and it worked for me.
I'm checking some issues like this and hope to have time to do a fork an PR

**Comment by comur** [comment]
Cool, thanks for your help !

**Comment by comur** [comment]
Too old. I close. Feel free to open new issue if you have any problem
