### ISSUE TITLE
how to translate

### ISSUE THREAD

**Issue by kikdu** [comur/ComurImageBundle#82]
Hello

How do we do to translate the bundle ? 

If I want to put it in french I have to change 

translation_domain: 'ComurImageBundle'

to

translation_domain: 'fr'

?

And apart from that we have to do something with the translation-bundle that we have installed in the same time of ComurImageBundle in the composer ?

Thanks!

**Comment by comur** [comment]
Hi @kikdu 

French translation already exists in the bundle so you just have to use it by putting your locale to 'fr'. 
If you want to be able to switch between two or more languages, you can do it like this:
http://stackoverflow.com/questions/17243426/change-locale-symfony-2-3

For more info about translation domain and other stuff: http://symfony.com/doc/current/components/translation.html
