### ISSUE TITLE
Unsuccessful upload without response

### ISSUE THREAD

**Issue by ignas3run** [comur/ComurImageBundle#83]
Whenever I try uploading file, progress bar stops at the end and nothing happens. Browser console is not giving any errors. Anyone know what might cause the problem?

`{% include "ComurImageBundle:Form:croppable_image_modal.html.twig" with {'include_jquery': false, 'include_bootstrap': false} %}`

I have my own bootstrap and jquery included before the modal in head tag.
![screenshot 2016-10-19 15 48 40](https://cloud.githubusercontent.com/assets/11816947/19521387/c0f4e078-9613-11e6-9c62-9e3d8c666bd3.png)

**Comment by ignas3run** [comment]
In the end after some waiting I got response:

> GET http://symfony.trainingexperience.org/uploads/profile-pictures/01038c471569a85c8eb10475e8b0a599f2e394c9.jpg?1476886343873 404 (Not Found)

I suppose it has to be a file that was being uploaded

**Comment by bhss** [comment]
How you solve you'r problèm i'm facing the same ??? some help here plz @ignas3run

**Comment by ignas3run** [comment]
@bhss I deleted the bundle since I couldn't figure it out.
