### ISSUE TITLE
Using on a non-bootstrap website

### ISSUE THREAD

**Issue by thelem** [comur/ComurImageBundle#85]
This bundle looks to be exactly what I'm after, but my website doesn't use bootstrap for its layout.

If I include the template using:

{% include "ComurImageBundle:Form:croppable_image_modal.html.twig" with {'include_jquery': false, 'include_bootstrap': false} %}

then I see the contents of the modal at the top of the page as soon as the page loads. If I remove the 'include_bootstrap': false then they bootstrap styling gets included and breaks the styling of the rest of my site.

I can't see a way around that other than removing the bundle's Bootstrap dependency. Bootstrap seems a huge dependency if it is just being used to create the modal.

**Comment by comur** [comment]
Hi @thelem 
Yes it's a dependency. But you can remove it and create a css to style it by yourself, I think it's a bit of work but possible. You need to hide the modal at the beginning and use bootstrap classnames (already used on components) to style them properly
