### ISSUE TITLE
Error: Call to a member function getUploadRootDir() on null

### ISSUE THREAD

**Issue by Alilou24** [comur/ComurImageBundle#87]
Hi,
I have this error:
Error: Call to a member function getUploadRootDir() on null
500 Internal Server Error - FatalErrorException

from symfony when I do this:
$picture = $builder->getForm()->getData();

I've tried many things but I didn't work.

Thanks.

**Comment by comur** [comment]
Too old. I close. Feel free to open new issue if you have any problem
