### ISSUE TITLE
Problem with datepicker and comurimage bundle

### ISSUE THREAD

**Issue by toullec** [comur/ComurImageBundle#95]
Hello,

I have problem with my comurimage bundle and my datepicker. When I include comurimage bundle, datepicker is not recognized in the console "datepicker() is not a function", and when I include comurbundle after datepicker function, I have an error about fileupload.js in the console but datepicker is recognized and works

Uncaught TypeError: $(...).fileupload is not a function
    at initializeImageManager (comur.imagelibrary.js:60)
    at HTMLDivElement.<anonymous> (/:591)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.r.handle (jquery.min.js:3)

ComurImage bundle include:
{% include "ComurImageBundle:Form:croppable_image_modal.html.twig"%}
<script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
<script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>

Jquery and css include:

<script src="/Symfony/web/bundles/comurimage/js/jquery.js"></script>

<script src="/Symfony/web/bundles/comurimage/js/jquery.ui.widget.js"></script>

<script src="/Symfony/web/bundles/comurimage/js/jquery.iframe-transport.js"></script>
<script src="/Symfony/web/bundles/comurimage/js/jquery.fileupload.js"></script>
<script src="/Symfony/web/bundles/comurimage/js/jquery.Jcrop.min.js"></script>
<script src="/Symfony/web/bundles/comurimage/js/jquery.color.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.5.2/holder.min.js"></script>
<script src="/Symfony/web/bundles/comurimage/js/bootstrap.min.js"></script>

<script src="/Symfony/web/bundles/comurimage/js/comur.imagelibrary.js"></script>

<link rel="stylesheet" href="/Symfony/web/bundles/comurimage/css/jquery.Jcrop.min.css" type="text/css" />

<link rel="stylesheet" href="/Symfony/web/bundles/comurimage/css/bootstrap.css" type="text/css" />
<link rel="stylesheet" href="/Symfony/web/bundles/comurimage/css/comur.image_bundle.css" type="text/css" />

<div id="image_upload_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3>Uploader image</h3>
</div>
<div class="modal-body">
<ul class="nav nav-pills" id="image_upload_tabs">
<li class="active">
<a href="#upload-image" data-toggle="tab">Uploader image</a>
</li>
<li><a href="#select-existing" data-toggle="tab">Sélectionner une image existante</a></li>
<li><a href="#crop-and-use" data-toggle="tab">Cropper et Utiliser</a></li>
</ul>
<div class="tab-content">

<div class="tab-pane active" id="upload-image">
<div class="field-error clearfix hidden">
<div id="image_upload_widget_error" class="alert alert-danger span6">
</div>
</div>
<div id="image_upload_drop_zone" class="image_upload_drop_zone">
<p>Glissez votre fichier ici</p>
<p>ou</p>
</div>
<div id="image_upload_file_container">
<span class="btn btn-info fileinput-button">
<i class="icon-white icon-download-alt"></i>
<span> Sélectionnez un fichier...</span>
<input id="image_upload_file" type="file" name="image_upload_file">
</span>
</div>
<div id="image_file_upload_progress" class="progress">
<div class="progress-bar progress-bar-success"></div>
</div>
</div>

<div class="tab-pane hidden" id="select-existing">
<div class="field-error clearfix hidden">
<div id="image_select_widget_error" class="alert alert-danger span6">
</div>
</div>
<div id="existing-images"></div>
<input type="hidden" id="selected_image"/>
</div>

<div class="tab-pane" id="crop-and-use">
<p>Veuillez ajuster la selection à votre image</p>
<div class="image_preview" id="image_preview" style="z-index: 1050">
<p>Veuillez uploader ou sélectionner une image existante</p>
</div>
</div>
</div>
<div class="modal-footer">
<button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
<span class="btn btn-success hidden" id="image_crop_go_now">
<i class="icon-white icon icon-fullscreen"></i>
Cropper & Utiliser ! </span>
<span class="btn btn-success hidden" id="image_crop_cancel">
<i class="icon-white icon icon-fullscreen"></i>
Cancel </span>
</div>
</div>
</div>
</div>
</div>
<script>
$('#image_upload_modal').on({
'hidden.bs.modal': destroyImageManager
});
</script>
<script src="/Symfony/web/bundles/fosjsrouting/js/router.js"></script>
<script src="/Symfony/web/app_dev.php/js/routing?callback=fos.Router.setData"></script>

<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png" />
<link rel="icon" type="image/png" href="assets/img/favicon.png" />

<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
<meta name="viewport" content="width=device-width" />

<link href="/Symfony/web/css/bootstrap.css" rel="stylesheet" />
<link href="/Symfony/web/css/custom.css" rel="stylesheet">

<link href="/Symfony/web/css/bootstrap-social.css" rel="stylesheet">
<link href="/Symfony/web/css/clean-blog.css" rel="stylesheet">
<link href="/Symfony/web/css/datepicker.css" rel="stylesheet">
<link href="/Symfony/web/css/font-awesome.css" rel="stylesheet">

<style>
.navbar-custom {
background-color: #25a45b;
position:fixed;
}

</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="/Symfony/web/js/bootstrap.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/js/bootstrap-datetimepicker.min.js"></script>

**Comment by comur** [comment]
Too old. I close. Feel free to open new issue if you have any problem
