### ISSUE TITLE
conflict with requirements symfony form (composer)

### ISSUE THREAD

**Issue by julianomcl** [comur/ComurImageBundle#98]
When I try to update composer I get a conflict message:

"comur/image-bundle 1.0.2 requires symfony/form ~2.2 -> [..] but these conflict with your requirements or minimum-stability."

I am using Symfony 3.2 with Symfony/Form 3.2. Is not possbile to use this component with these requirements?

Thanks

**Comment by comur** [comment]
Hi
you should use 1.3 branch, please open new issue if not ok
